version: "3"
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=UTC
      - PGID=1000
      - PUID=1000
    volumes:
      - ./homebridge:/homebridge
  automation:
    build: .
    depends_on:
      - homebridge
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped
