version: "3"
services:
  homebridge:
    build:
      context: .
      dockerfile: Dockerfile.homebridge
    restart: unless-stopped
    ports:
      - "8581:8581"
    volumes:
      - ./homebridge:/var/lib/homebridge
    environment:
      - TZ=UTC
  automation:
    build: .
    depends_on:
      - homebridge
    env_file:
      - .env
    restart: unless-stopped
