version: "3"
services:
  homebridge:
    build:
      context: .
      dockerfile: Dockerfile.homebridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./homebridge:/var/lib/homebridge
    environment:
      - TZ=UTC
  automation:
    build: .
    depends_on:
      - homebridge
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped
